package com.nexuslink.wenavi;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.nexuslink.wenavi.FriendVerify;

import com.nexuslink.wenavi.FriendVerifyDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig friendVerifyDaoConfig;

    private final FriendVerifyDao friendVerifyDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        friendVerifyDaoConfig = daoConfigMap.get(FriendVerifyDao.class).clone();
        friendVerifyDaoConfig.initIdentityScope(type);

        friendVerifyDao = new FriendVerifyDao(friendVerifyDaoConfig, this);

        registerDao(FriendVerify.class, friendVerifyDao);
    }
    
    public void clear() {
        friendVerifyDaoConfig.getIdentityScope().clear();
    }

    public FriendVerifyDao getFriendVerifyDao() {
        return friendVerifyDao;
    }

}
